### ISSUE TITLE
Play button non functional

### ISSUE THREAD

**Issue by theraineydaze** [Martin-Oehler/SteamVR-WebApps#1]
Installed with no problems and logged in with Facebook. The interface works perfectly except every play button does not press. No music plays but whatever is clicked to play its added to the "Recently played" list.

**Comment by Martin-Oehler** [comment]
This is due to DRM reasons. Please read the _Usage_ section of the [readme](https://github.com/Martin-Oehler/SteamVR-WebApps/blob/master/SteamVR-Spotify/README.md).

**Comment by theraineydaze** [comment]
I thought I read this the whole Readme but totally missed this. Sorry! I feel dumb now, works great!
